name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: FileShare on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build FileShareCli
        run: ./gradlew nativeCompile

      - name: Debug
        run: ls -alR

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fileshare-${{ matrix.os }}
          path: ./build/native/nativeCompile/fileshare*